version: "3"
services:
  client:
    image: "diegoleoro/multi-client-10-14"
    mem_limit: 128m
    hostname: client
  server:
    image: "diegoleoro/multi-server-10-14"
    mem_limit: 128m
    hostname: api
    environment:
      - REDIS_HOST=$REDIS_HOST
      - REDIS_PORT=$REDIS_PORT
      - PGUSER=$PGUSER
      - PGHOST=$PGHOST
      - PGDATABASE=$PGDATABASE
      - PGPASSWORD=$PGPASSWORD
      - PGPORT=$PGPORT
  worker:
    image: "diegoleoro/multi-worker-10-14"
    mem_limit: 128m
    hostname: worker
    environment:
      - REDIS_HOST=$REDIS_HOST
      - REDIS_PORT=$REDIS_PORT
  nginx:
    image: "diegoleoro/multi-nginx-10-14"
    mem_limit: 128m
    hostname: nginx
    ports:
      - "80:80" # to expose traffic to our group of containers, we need to open up a port in the nginx service

      # we are saying 'open up the port 80 on the machine that is hosting all of our containers and map that to port 80 inside of the container, which is the default port that nginx listens to inside of the container '

